remote_theme: rohanchandra/type-theme

# SITE CONFIGURATION
baseurl: "/"
url: "https://digilegislativacz.github.io/"



# THEME-SPECIFIC CONFIGURATION
theme_settings:
  site_navigation_sort: "order"
  # Meta
  title: digilegislativa.cz
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "DigitÃ¡lnÄ› pÅ™Ã­vÄ›tivÃ¡ legslativa a DigitÃ¡lnÃ­ legislativa pro 21. stoletÃ­"

  # Header and footer text
  header_text: >

  header_text_feature_image:
  footer_text: >
    <p>Â© 2020 digilegislativa.cz a michalrada.cz</p>

  # Icons
  rss: true
  email_address: 
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  gitlab:
  github: 
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Najdi mÄ› na"
  str_rss_follow: "RSS"
  str_email: "Email"
  str_next_post: "DalÅ¡Ã­ ÄlÃ¡nek"
  str_previous_post: "PÅ™edchozÃ­ ÄlÃ¡nek"
  str_next_page: "DalÅ¡Ã­ strÃ¡nka"
  str_previous_page: "PÅ™edchozÃ­ strÃ¡nka"
  str_continue_reading: "âž¡ ÄŒÃ­st dÃ¡l..."
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "ðŸ˜¢ Nic jsme nenaÅ¡li."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
